### ISSUE TITLE
Integration with Cohere

### ISSUE THREAD

**Issue by nicolomonti** [pieroit/cheshire-cat#1]
Cohere exposes LLMs for free through their API, I think this could be very beneficial both for fast and free iteration during development, and to the users who cannot afford to use the OpenAI api

**Comment by pieroit** [comment]
thanks! will add soon

**Comment by pieroit** [comment]
integration with Cohere has been added but not yet tested:
- see config class: https://github.com/pieroit/cheshire-cat/blob/main/web/cat/config/llm.py#L41
- see plugin example on how to use a custom LLM here: https://github.com/pieroit/cheshire-cat/blob/main/web/cat/plugins/quickstart_cat_plugin/models.py

Still raw but can work

**Comment by pieroit** [comment]
@nicolomonti I added support for Cohere both fir LLM  and embedder.
The model is hallucinating a lot, so I don't know if it requires special prompting or a specific data structure in the request. At the moment we are just pigging back on langchain Cohere adapters.

![Screenshot from 2023-04-07 16-16-05](https://user-images.githubusercontent.com/6328377/230626722-a2cb454a-e012-41d6-b545-89592d32e244.png)


I tried them out in a separate notebook, outside of the cat and there are still hallucinations:

![Screenshot from 2023-04-07 16-08-31](https://user-images.githubusercontent.com/6328377/230626751-efcb176e-38e1-47ad-bef9-7f9ac83f2215.png)

Closing this issue and opening a new one specific for this problem. Please le me know if you are interested in investigating

**Comment by pieroit** [comment]
@nicolomonti opend issue #82
