### ISSUE TITLE
Make ingest_file in "cat/rabbit_hole.py" a method in the CheshireCat class

### ISSUE THREAD

**Issue by nicola-corbellini** [pieroit/cheshire-cat#102]
It could be useful to have the function as a method in the main class of the Cat to make an instance of the cat use it directly, without making a request to the rabbit_hole endpoint. In this way, you can use it directly inside a tool and ask the cat to ingest files.

E.g. I write a tool to download a .pdf from the web and make the cat ingest it with natural language

**Comment by pieroit** [comment]
@calebgcc sounds a great idea
