### ISSUE TITLE
Add a WorkingMemory class

### ISSUE THREAD

**Issue by pieroit** [pieroit/cheshire-cat#103]
Episodic and Declarative memory contents that are relevant and inserted into the prompt should be managed by a separated class `WorkingMemory` so they can be not only used in the prompt, but also in plugins and in the rabbit hole.
This opens up *a lot* of use cases

@calebgcc @nickprock @peppicus  what do you think?

**Comment by pieroit** [comment]
A Working memory as proposed by @nicola-corbellini is not only a good idea to pass short-term lived information around (in both core and plugins), but also coherent with the idea of a cognitive architecture.

We could create a little class `WorkingMemory` in `core/cat/memory/working_memory.py`. An instance of this class is attached as attribute to the cat so we can do `cat.working_memory.something()`

It should encapsulate a dictionary in which both the core and plugins can store arbitrary information. At execution time we can add content to the working memory with something like:

`cat.working_memory.keep_in_mind("custom-key", custom_content)`

There may be utility methods like:

`working_memory.reset()`
`working_memory.forget("custom-key")`

And in any case one should be able to directly manipulate the dictionary with something like

`working_memory["custom-key"] = [1, 2, 3]`

For this latest case, we can rely to python [magic methods](https://www.geeksforgeeks.org/__getitem__-and-__setitem__-in-python/) to make the whole instance act as a dictionary :dancers: 

When this is done I will try to let langchain write the agent steps into the working memory so the prompting cycle is available and the `why` can be accessible from plugins

As a final note, recent [conversation history](https://github.com/pieroit/cheshire-cat/blob/main/core/cat/looking_glass/cheshire_cat.py#L101) should be easily incapsulated in the working memory instead of begin directly attached to the cat. See for example issue #172  

@nicola-corbellini if you comment this issue I'll assign to you, thanks!
@calebgcc also your view on this would be helpful

**Comment by nicola-corbellini** [comment]
I have to correct my last comment: I was reasoning about the implementation and a couple of doubts popped to my mind.

Both these methods:
`working_memory.reset()`
`working_memory.forget("custom-key")`
are already `dict` built-in  methods. Namely, `dict.clear()` and `dict.pop("custom-key")`.

Moreover, you, @pieroit, stated that devs should be able to directly manipulate the `cat.working_memory` instance, that should act like a dictionary. 
Thus, I asked myself: is a `WorkingMemory` class really necessary? 

The answer I gave to myself is to create something as simple as:
```python
class WorkingMemory(dict):
    def __init__(self):
        super().__init__(history="")
```
In this way the `working_memory` instance would behave like a dict, ready to be extended/overridden with custom methods or overriding magic methods. Also, it encapsulates the conversation history, that is reset every time the cat is (re)instantiated.

Does this make sense to you or am I missing something?

**Comment by pieroit** [comment]
> The answer I gave to myself is to create something as simple as:
> 
> ```python
> class WorkingMemory(dict):
>     def __init__(self):
>         super().__init__(history="")
> ```
> 
> In this way the `working_memory` instance would behave like a dict, ready to be extended/overridden with custom methods or overriding magic methods. Also, it encapsulates the conversation history, that is reset every time the cat is (re)instantiated.
> 
> Does this make sense to you or am I missing something?

100% on board with this!
Thanks
