### ISSUE TITLE
Error installing: "exec /bin/sh: exec format error"

### ISSUE THREAD

**Issue by xifi-kif** [pieroit/cheshire-cat#104]
Hello, this seems a great project!

Unfortunately, I'm running into an issue while trying to install cheshire-cat: I've installed docker and docker-compose and cloned the repo, but right after running docker-compose up i get this:

```
# docker-compose up
[+] Building 1.4s (6/9)
 => [internal] load build definition from Dockerfile                                             0.0s
 => => transferring dockerfile: 359B                                                             0.0s
 => [internal] load .dockerignore                                                                0.0s
 => => transferring context: 2B                                                                  0.0s
 => [internal] load metadata for docker.io/tiangolo/uvicorn-gunicorn:python3.9                   0.9s
 => CACHED [1/5] FROM docker.io/tiangolo/uvicorn-gunicorn:python3.9@sha256:23c1b629cd7c84f2b401  0.0s
 => [internal] load build context                                                                0.0s
 => => transferring context: 38B                                                                 0.0s
 => ERROR [2/5] RUN apt-get update -y                                                            0.4s
------
 > [2/5] RUN apt-get update -y:
#0 0.409 exec /bin/sh: exec format error
------
failed to solve: process "/bin/sh -c apt-get update -y" did not complete successfully: exit code: 1
```

Can't find any useful log :(
Searched the internet and this maybe related to differtent architectures between the docker image(s) and my host. I'm quite new to docker and maybe I'm wrong, but since my host is arm aarch64, maybe it is still not compatible with this?

**Comment by pieroit** [comment]
shut down everything
`docker-compose down`

and then rebuild without using cache
`docker-compose build --no-cache`

**Comment by xifi-kif** [comment]
same error, even with --no-cache

**Comment by pieroit** [comment]
> maybe I'm wrong, but since my host is arm aarch64, maybe it is still not compatible with this?

I don't know honestly, sorry. :(
The error is on the `apt-get update` command during image building, which is not related to the cat. I'll leave the issue open in case someone could help.

**Comment by Mte90** [comment]
So I am not a Docker expert but I think that the image has some issues with bash.

https://beebom.com/how-fix-exec-user-process-caused-exec-format-error-linux/

Looking here seems that the image is for amd64 but you are running somewhere else. Maybe you are using Arm64 on OSX as example?

**Comment by anninasim** [comment]
# docker-compose up
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dcheshire-cat%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.

Non riesco più ad aprire cheshire cat e non so come risolvere. Nella prima installazione funzionava tutto correttamente ma ora non capisco dove sia il problema. Premetto che non sono un'esperta del settore ma di fronte a queste iniziative amo sperimentare

**Comment by Mte90** [comment]
@anninasim open a new ticket as the error is completely different and just use english as this project is international :-)

**Comment by pieroit** [comment]
Closing this as it is probably a problem of docker vs system architecture
