### ISSUE TITLE
Code quality on PRs

### ISSUE THREAD

**Issue by Mte90** [pieroit/cheshire-cat#106]
So to move on the python code quality the ideal is to add a GH action executed on PRs that check code quality.

Python has https://pypi.org/project/autopep8/ (to fix issues) and https://pypi.org/project/pylint/ that suggest how to do things better.
This repo has also the JS stuff but that complicates a lot of things (and probably is better a different repository for that).

I think that right now is important to improve the code quality, also because check if documentation is missing as example (and autofix various errors).
Slowly also the settings can be changed to ignore some errors and so on. Also because fix pep8 errors can be also a task for new comers (for the actual code base) and we can remove that documentation task from https://github.com/pieroit/cheshire-cat/issues/63

Ref: https://github.com/marketplace/actions/autopep8
For pylint is enough to download it and execute it

**Comment by Mte90** [comment]
> I guess a GH action is also useful.

The difference is that in this way you are sure that any PR is checked because not everyone use `precommit` so the review task is more easy.

> Did not understand this, can you clarify?

So the point is that when you will enable pylint/autopep8 (on the whole codebase) it will report errors everywhere but the project works, so the task to fix those errors is something that new contributors can do without problems. Also maybe both reports errors that for the project aren't so the settings for the tool can be fined later.

**Comment by Mte90** [comment]
So it is time to thinking what the CI should have for the linting stuff:

* https://github.com/skhomuti/pylint-actions to report issues in the code
* https://github.com/marketplace/actions/autopep8 to autoformat and update the PR, automatically open a new PR with the fixes
  * I don't like that approach so much but can be helpful when you have to prepare for a release
  * It is executed automatically after a PR is merged and the PR is opened if there are issues
* https://github.com/tonybaloney/perflint - this one is very powerful and reports where the code can be written in a more performance wise manner
  * I have to check on how to use it in a CI

**Comment by pieroit** [comment]
> So it is time to thinking what the CI should have for the linting stuff:
> 
> * https://github.com/skhomuti/pylint-actions to report issues in the code
> * https://github.com/marketplace/actions/autopep8 to autoformat and update the PR, automatically open a new PR with the fixes
>   
>   * I don't like that approach so much but can be helpful when you have to prepare for a release
>   * It is executed automatically after a PR is merged and the PR is opened if there are issues
> * https://github.com/tonybaloney/perflint - this one is very powerful and reports where the code can be written in a more performance wise manner
>   
>   * I have to check on how to use it in a CI

Thanks. Let's start with a **minimal setup**, also taking into account what is happening in PR #252
