### ISSUE TITLE
Forgetful Websocket Call

### ISSUE THREAD

**Issue by webgrafia** [pieroit/cheshire-cat#116]
It would be useful to implement the possibility of making websocket calls that are not stored and therefore do not feed the cheshire database.
In the typical use case of a chatbot exposed as a search service on internal data, it is essential not to allow users to "dirty" the database with their inputs.
Having the possibility to make calls to the ws endpoint declaring that they must be "forgetful" opens the way to different uses of the platform.

**Comment by pieroit** [comment]
This can now be done with a plugin using hooks
(please be patient as hooks are not yet documented, but the defaults can be found [here](https://github.com/pieroit/cheshire-cat/tree/main/core/cat/mad_hatter/core_plugin/hooks))
