### ISSUE TITLE
Feature Request: Ingest Website content using URL

### ISSUE THREAD

**Issue by calebgcc** [pieroit/cheshire-cat#125]
It might be helpful if the cat could ingest web content such as blogs or Wikipedia articles through a link.
This should be treated exactly like the ingestion of documents. (parsing, summarization, storing, ...)

**Comment by pieroit** [comment]
@calebgcc agree!
Let's start from a simple URL

**Comment by pieroit** [comment]
It also opens up possibility to make a browser extension for the cat
