### ISSUE TITLE
Installation procedure

### ISSUE THREAD

**Issue by quonn77** [pieroit/cheshire-cat#149]
Using latest version of docker-composed (2.17.3) under my old ubuntu 16.04 I faced into this issue:
`failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to mount `

I solved it setting the following environment variables priori to run docker-compose up
```bash
export DOCKER_BUILDKIT=0
export COMPOSE_DOCKER_CLI_BUILD=0
```
Thank you very much for sharing your project with the community.
Grazie mille !! :-)

**Comment by pieroit** [comment]
Thank you @quonn77 
Is this bug due to the latest docker version or die to the old ubuntu version?

**Comment by quonn77** [comment]
Ciao Pietro. I don't know if it is due to the old ubuntu or to the newest
docker-compose I am using...just because actually I don't have a different
platform where I can try "Stregatto". I will retry, maybe,  in the middle
of may  on a Windows Platform. I will inform you if this happens also there.

Il giorno ven 21 apr 2023 alle ore 10:52 Piero Savastano <
***@***.***> ha scritto:

**Comment by pieroit** [comment]
@quonn77 should work easy on windows always through docker! Let me know
