### ISSUE TITLE
Admin doesn't able to connect

### ISSUE THREAD

**Issue by suxper** [pieroit/cheshire-cat#150]
Hi all,

after launching the command docker-compose up I try to connect to localhost:3000 but it fails. 
In the docker log I see this error:

admin          | failed to load config from /app/vite.config.ts
admin          | error when starting dev server:
admin          | Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/app/node_modules/css-has-pseudo/dist/index.mjs' imported from /app/node_modules/postcss-preset-env/dist/index.mjs
admin          | Did you mean to import css-has-pseudo/dist/index.cjs?
admin          |     at new NodeError (node:internal/errors:399:5)
admin          |     at finalizeResolution (node:internal/modules/esm/resolve:326:11)
admin          |     at moduleResolve (node:internal/modules/esm/resolve:945:10)
admin          |     at defaultResolve (node:internal/modules/esm/resolve:1153:11)
admin          |     at nextResolve (node:internal/modules/esm/loader:163:28)
admin          |     at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
admin          |     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
admin          |     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
admin          |     at link (node:internal/modules/esm/module_job:76:36)

What I should do?

Thanks

**Comment by pieroit** [comment]
reinstall from scratch, and git pull the latest version. Follow readme instructions, there is a new version

**Comment by suxper** [comment]
Thanks now it's working
