### ISSUE TITLE
Impossible to configure a language model. error 403

### ISSUE THREAD

**Issue by requies** [pieroit/cheshire-cat#152]
Impossible to configure a language model.
Error 403

![Screenshot_20230421_130205](https://user-images.githubusercontent.com/2270251/233621519-ba59b026-5bdd-45ce-a404-873d6902ffc8.png)

**Comment by pieroit** [comment]
show me the terminal error

**Comment by requies** [comment]
> show me the terminal error

![Screenshot_20230421_130205](https://user-images.githubusercontent.com/2270251/233622338-a49d575c-6352-4127-bf01-3913861df431.png)

**Comment by niatro** [comment]
Hi exactly the same with me!!

**Comment by pieroit** [comment]
@niatro @requies did you configure the .env files copying the .env.example?
It has changed yesterday

**Comment by requies** [comment]
@pieroit yes.

Looks like it's looking for the settings from the IP 172.20.0.1 while the pc assigned IP (after docker-compose up) is 172.23.0.4.

**Comment by niatro** [comment]
> @niatro @requies did you configure the .env files copying the .env.example? It has changed yesterday

Yes I changed properly... I think. Please watch
![image](https://user-images.githubusercontent.com/34010695/233748164-62c71822-ea9b-42d8-8890-2bb100ce8d5c.png)

I retouched my opena_ai key

**Comment by niatro** [comment]
![image](https://user-images.githubusercontent.com/34010695/233748283-5504c5f5-c9b8-49ef-916a-b33811bb043f.png)

Yes I changed properly...  I think (I retouched my api token dont worry)

**Comment by pieroit** [comment]
> ![image](https://user-images.githubusercontent.com/34010695/233748283-5504c5f5-c9b8-49ef-916a-b33811bb043f.png)
> 
> Yes I changed properly... I think (I retouched my api token dont worry)

Man, comment the api_key line!
Otherwise every request must contain the key. That is only for security and if you access the cat via api

**Comment by niatro** [comment]
OK...  then lets try

**Comment by niatro** [comment]
Ok Piero now works and I understood the new mechanical for apis keys, but after configure my model in settings I still get messages from Cat asking for configure the Language Model

**Comment by pieroit** [comment]
@niatro yes that may be a bug, track the error in the terminal

**Comment by pieroit** [comment]
@requies @niatro I found the bug about the language model switch, sorry for the inconvenience. It was introduced yesterday after updating the plugin system.

Can you pull the latest version and verify everything works?
Thanks for reaching out

**Comment by requies** [comment]
@pieroit Now it works flawlessy.

Thank you !!

**Comment by niatro** [comment]
"Hello Piero, I can confirm that the issue has been resolved and everything is functioning properly after following the complete update process (beyond simply performing a git pull). On a related note, I noticed that the output from the cat is rather brief, despite being connected to the OpenAI API. Is there a specific location in the code where we can define the maximum number of tokens we'd like to receive from the model? Thank you."

**Comment by pieroit** [comment]
> Is there a specific location in the code where we can define the maximum number of tokens we'd like to receive from the model? Thank you.

Should be possible by giving a default to the config class, and it will show up in the admin
https://github.com/pieroit/cheshire-cat/blob/main/core/cat/factory/llm.py#L54

Should be something like `max_tokens`, you should check out in the corrispective langchain class
