### ISSUE TITLE
smaller docker image for Admin

### ISSUE THREAD

**Issue by PaperBackPear3** [pieroit/cheshire-cat#170]
Using node18-slim image for **Admin**, makes it way smaller 

**Node18:**
![image](https://user-images.githubusercontent.com/44753919/234247621-44a5801e-0330-4f6b-bba6-9c2d362260a4.png)

**Node18-Slim:**
![image](https://user-images.githubusercontent.com/44753919/234246417-da46fb4b-f7c5-441f-a9df-cf9a7254da40.png)

without compromising functionalities

**Comment by pieroit** [comment]
I'm reading feedback on this slim version and it seems it may be risky with tooling like Vite.
Also we will probably move to a static deploy of the admin at some point, so no stress :)
Thank you for suggesting!
