### ISSUE TITLE
After today Update "Something went wrong... "

### ISSUE THREAD

**Issue by niatro** [pieroit/cheshire-cat#174]
Hi Guys,
after today update with procedure
"docker-compose down
git pull origin main
docker-compose build --no-cache
docker-compose up" I got the following error

<img width="397" alt="msedge_GMWULA4sQI" src="https://user-images.githubusercontent.com/34010695/234566869-5ea483fa-6359-4276-bb6d-02fa5e416694.png">

Console dont show something special

<img width="627" alt="WindowsTerminal_yLRgzZcv1V" src="https://user-images.githubusercontent.com/34010695/234567140-f847b95c-f6bc-49ed-bdb2-7af71814b5f2.png">

When try to connect plugins "Failed to fetch"
![image](https://user-images.githubusercontent.com/34010695/234567355-0890964c-1d61-45d9-afe6-a732b05660ad.png)

When try to configure languaje model "Failed to fetch"
![image](https://user-images.githubusercontent.com/34010695/234567606-91232c46-df2e-401a-8279-4bd056e4ca64.png)

Inspecting page in console I found this:
![image](https://user-images.githubusercontent.com/34010695/234568103-51e4f4c7-4a1a-4f2a-a772-eadb33717aa9.png)
Some ideas?

**Comment by pieroit** [comment]
Show me you .env

**Comment by niatro** [comment]
There is
![image](https://user-images.githubusercontent.com/34010695/234570362-7a9a38b6-757f-4fa2-83d8-9a402f3ddc5d.png)

**Comment by pieroit** [comment]
@niatro there should be an error in the terminal saying why request was denied, can you track it down?
Also, what do you see on `localhost:1865/docs` ?

**Comment by niatro** [comment]
Hi @pieroit, I've encountered several times the sam
[Console_log.txt](https://github.com/pieroit/cheshire-cat/files/11361797/Console_log.txt)
 errors in the console prior to navigating to the local link (Local: http://localhost:3000/). Specifically, I observed httpcore.ConnectError: [Errno 111] Connection refused errors on the following console lines: 131, 140, 165, 186, and 222.

I've attached a file containing the complete console log for your reference. Additionally, I'd like to mention that the localhost:1865/docs endpoint is not accessible under the current circumstances.

Please let me know if you require any further information or if there's anything else I can do. Thanks!

**Comment by pieroit** [comment]
@niatro what do you see if you do "docker ps -a"

I have the impression you started the cat twice or ports are reserved from another application

**Comment by niatro** [comment]
Hi @pieroit, I've checked the list of containers using the `docker ps -a` command and found that there were no running containers. As a test, I performed the standard procedure for running the application (using `docker-compose down` and `docker-compose up`). This time, the application worked without any issues.

I suspect that the error might have been caused by not properly shutting down containers in my previous attempts. Thanks to your guidance and my additional testing, the application is now functioning correctly. You may close the issue. I appreciate your help!
