### ISSUE TITLE
[Core] Find plugins search also in md files

### ISSUE THREAD

**Issue by Mte90** [pieroit/cheshire-cat#179]
Line: https://github.com/pieroit/cheshire-cat/blob/main/core/cat/mad_hatter/mad_hatter.py#L26

![immagine](https://user-images.githubusercontent.com/403283/234920127-d018a4f0-b31a-48a0-a4f8-fb19dd7bf4ef.png)

**Comment by pieroit** [comment]
Search is restricted to python files:
https://github.com/pieroit/cheshire-cat/blob/main/core/cat/mad_hatter/mad_hatter.py#L34

And plugin.json
https://github.com/pieroit/cheshire-cat/blob/main/core/cat/mad_hatter/mad_hatter.py#L77

**Comment by Mte90** [comment]
No it is wrong, the code search for files and folders as per line https://github.com/pieroit/cheshire-cat/blob/main/core/cat/mad_hatter/mad_hatter.py#L28 but doesn't check if it is really a folder.
As you can see in the screen was looking for files inside a md file

**Comment by pieroit** [comment]
Ok got it @Mte90 thanks.
Do you know how to fix this? Should not be a problem because in the end only python files are included, but if you want you can open a PR for a more strict search

**Comment by Mte90** [comment]
it should do just a check if ti si a folder, it is something I can do but the ticket need to be reopened :-)
