### ISSUE TITLE
[Core] Hooks list should show the function not the memory address

### ISSUE THREAD

**Issue by Mte90** [pieroit/cheshire-cat#180]
If we want that the log is helpful:

![immagine](https://user-images.githubusercontent.com/403283/234920468-a7b3ff2b-9218-43db-91f8-a55f6bf2dbf8.png)

the `hook_function` parameter should be the function name as as it is now doesn't show any helpful hints

**Comment by pieroit** [comment]
It has to be the same as `hook_name`, otherwise the cat does not run them

Inserting there plugin_name could also be helpful

What about a call to talk about pluggy?
Cannot understand if it allows an easy to use plugin api as the one we have (only decorators, no explicit registration)

**Comment by pieroit** [comment]
This one has been fixed in #202
