### ISSUE TITLE
Summarization chain should work on doc.page_content and not on the doc object

### ISSUE THREAD

**Issue by pieroit** [pieroit/cheshire-cat#185]
Found a bug, the summarization parses stringified docs instead of directly the text

![Screenshot from 2023-04-28 17-48-19](https://user-images.githubusercontent.com/6328377/235194693-bc1ab2ff-3b6f-4216-9614-cdfc269db238.png)

Are you available to fix this @calebgcc ? If not I'll do it ;)

**Comment by calebgcc** [comment]
that's odd, could it be related to our custom summarization chain?

We are passing a list of documents as input to our custom chain, as is also done in the langchain summary chain, but maybe they have overwritten the method to handle it differently.
Or maybe it was always like this and we didn't notice ahhaha

anyway, I can work on that in the next couple of days, so if you want to solve it it's all yours :3
