### ISSUE TITLE
bootstrap documentation with a small web presence

### ISSUE THREAD

**Issue by pieroit** [pieroit/cheshire-cat#19]
Before docs, let's have a few pages for the project directly on github pages.

**Comment by Mte90** [comment]
Includes also some screenshots of the web interface and how works, not just how to setup.

**Comment by pieroit** [comment]
Github pages for this project are up, [this is the link](https://pieroit.github.io/cheshire-cat/)

Content can be edited in the `docs` folder

**Comment by pieroit** [comment]
Moved docs in the gh-pages branch.
Please see issue #57
