### ISSUE TITLE
Power Point with the cat

### ISSUE THREAD

**Issue by LinuxTux193** [pieroit/cheshire-cat#199]
HI, i have some powerpoints to analyze, can i upload it to the cat and ask question about this ppt?
Thanks in advance

**Comment by antomanc** [comment]
I don't think there is already support for PowerPoint files, but you can extract the text from the PowerPoints files and put it in a pdf. However this maybe something that is good to be added in the future.

**Comment by pieroit** [comment]
@LinuxTux193 @antomanc in the future we may add support for additional file types (.ppt, .xlsx), at the moment we just ingest text.

There is a possibility that additional file types may be managed by plugins ;)

Closing for now

**Comment by xdatap1** [comment]
> HI, i have some powerpoints to analyze, can i upload it to the cat and ask question about this ppt?
> Thanks in advance

I do this by exporting them to PDF. I haven't found anything that gets lost in PDF conversion from the conversational point of view.
