### ISSUE TITLE
local environment and ensure codebase consistency and maintainability

### ISSUE THREAD

**Issue by umbertogriffo** [pieroit/cheshire-cat#21]
Hi there!

I have enjoyed looking at this project and appreciate your effort in making it functional and easy to use. However, I have noticed that there is no way to set up a `local environment` using tools like `pipenv`, which can help manage dependencies outside the Docker container.

I think it would be beneficial to have this option available because it would make it easier for developers to work on the project without relying solely on the Docker container. Additionally, it would allow for greater flexibility regarding the tools and versions of packages that developers can use.

Furthermore, I believe introducing code auto reformatting, PEP 8 checker (flake8), and auto sort imports (isort) with `pre-commit` would be a good idea. This would help ensure that the codebase remains consistent and maintainable over time.

If you agree, I can introduce all of them in a PR.

**Comment by pieroit** [comment]
Thanks for taking the time @umbertogriffo.

> I think it would be beneficial to have this option available because it would make it easier for developers to work on the project without relying solely on the Docker container. Additionally, it would allow for greater flexibility regarding the tools and versions of packages that developers can use.

The vision for the cat is a one command setup, with only one dependency (docker). But I gave a thought on your proposal because I see the point of using the cat as a library and outside docker.
The main obstacle I see is: if you start the cat with pip locally, how are you going to start the vector db and other coming dbs? (there will probably be an SQL)

A solution can be:
- use FAISS instead of Qdrant, because it relies on simple files and not on a microservice
-  use sqlite instead of postgres, for the same reason

And then let the user configure more powerful dbs, alà Django.
This can be done but requires way more maturity and abstraction. And most importantly, setting up systems like Django with docker is painful.
Any ideas? 

> Furthermore, I believe introducing code auto reformatting, PEP 8 checker (flake8), and auto sort imports (isort) with `pre-commit` would be a good idea. This would help ensure that the codebase remains consistent and maintainable over time.

Never used them but I trust you it can be useful. Can you help me on this for a start?

Thanks

**Comment by umbertogriffo** [comment]
Thanks for your responsiveness!

> The vision for the cat is a one command setup, with only one dependency (docker). But I gave a thought on your proposal because I see the point of using the cat as a library and outside docker.
> The main obstacle I see is: if you start the cat with pip locally, how are you going to start the vector db and other coming dbs? (there will probably be an SQL)
> 
> A solution can be:
> 
> use FAISS instead of Qdrant, because it relies on simple files and not on a microservice
> use sqlite instead of postgres, for the same reason
> And then let the user configure more powerful dbs, alà Django.
> This can be done but requires way more maturity and abstraction. And most importantly, setting up systems like Django with docker is painful.
> Any ideas?

The idea is not to replace docker, but to add also something useful for those who want to develop/debug locally. 
I would just decouple the dependencies [here](https://github.com/pieroit/cheshire-cat/blob/main/web/Dockerfile#L7) defining a `pipfile` (with a related `pipfile.lock` to have safe deployment in prod) containing all the dependencies, and then copy and install them into the docker image with something like:

```yaml
# Install python dependencies in /.venv
COPY Pipfile .
COPY Pipfile.lock .

RUN PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy
```
With the external `pipfile`, it will be easier for a dev makes changes on the core or write/test plugins locally.
The DBs (vector-based or relational) can still run on docker. When I develop the code, I can just run the specific services that I need without running the `cat` container.

> Never used them but I trust you it can be useful. Can you help me on this for a start?

Sure thing! I'll open a PR, and we can discuss things there.

**Comment by pieroit** [comment]
Sorry I'm not convinced it is worth it to switch from simple pip to pipenv. I will consider it later on.
One thing we can do is move requirements outside the Dockerfile and move them into a requirements.txt

**Comment by umbertogriffo** [comment]
Fair enough! Moving them into a `requirements.txt` would still be a nice starting point.
