### ISSUE TITLE
Admin container start with error

### ISSUE THREAD

**Issue by rinocovelli** [pieroit/cheshire-cat#210]
Dear friends, I'm trying to install cheshire-cat following the guide at this link:

[cheshire-cat](https://github.com/pieroit/cheshire-cat)

After the **docker-compose up** command I'm getting this error:

> cheshire_cat_admin exited with code 135
> cheshire_cat_admin          |
> cheshire_cat_admin          | up to date, audited 518 packages in 2s
> cheshire_cat_admin          |
> cheshire_cat_admin          | 172 packages are looking for funding
> cheshire_cat_admin          |   run `npm fund` for details
> cheshire_cat_admin          |
> cheshire_cat_admin          | found 0 vulnerabilities
> cheshire_cat_admin          |
> cheshire_cat_admin          | > ccat-admin@1.0.0 dev
> cheshire_cat_admin          | > vite --no-open
> cheshire_cat_admin          |

and the **cheshire_cat_admin** container is restarting many time.
Can you give me some suggestion about this error?

**Comment by pieroit** [comment]
It's an npm error
Delete the whole folder and try again

Follow the new tutorial
https://youtu.be/Rvx19TZBCrw

**Comment by pieroit** [comment]
Also, you should not run docker as sudo

**Comment by luca1844** [comment]
I try more times: the problem is related to settings of network (DNS).

Possible solution -> execute:
```
sudo cat << 'EOF' >> /etc/resolv.conf
nameserver 1.1.1.1
nameserver 1.0.0.1
EOF
```

It's necessary to execute docker-compose with sudo in a new installation (for network permissions).

**Comment by pieroit** [comment]
The admin is now included in the core and can be accessed via `localhost:1865/admin`
