### ISSUE TITLE
Redirect to docs when pinging root endpoint

### ISSUE THREAD

**Issue by valentimarco** [pieroit/cheshire-cat#217]
As write. 
Personally, i like it more than a simple json.
7669c214c01709c7e50862c7d60ebd5775fa8391

**Comment by pieroit** [comment]
It's ok if you want to add the docs URL to the json, but a redirect assumes there is a browser as a client (that is not the case as it may be another server, a voice interface, a car or something else

**Comment by valentimarco** [comment]
root endpoint is use only to ping the backend?

**Comment by pieroit** [comment]
Yes it is common to show a status message and version (agree on the docs url)

**Comment by valentimarco** [comment]
ok, i will rollback
