### ISSUE TITLE
Enable file-based upload of textual content via REST endpoint

### ISSUE THREAD

**Issue by antonioru** [pieroit/cheshire-cat#22]
Currently, the user can only add textual content to the cat by manually typing it in, which can be tedious and time-consuming. Therefore, we need to add a new feature that allows the user to add large amounts of textual content to the cat through a file uploader.

To implement this feature, we need to create an HTTP POST request that sends the selected file to the REST endpoint that accepts files. We also need to wait for the API response to ensure that the file was uploaded successfully. Once the file is uploaded, we will be able to process the content and add it to the cat.

This feature will provide users with an easy and efficient way to add textual content to the cat, which will improve the overall user experience

**Comment by pieroit** [comment]
At the moment the endpoint replies as soon as the file is uploaded, then proceeds async to parse it and upload contents to vector db.
Let's discuss later on how to notify the frontend about the successfull parsing, which is necessary
