### ISSUE TITLE
Hook to deactivate HyDE embedding [BUG]

### ISSUE THREAD

**Issue by rpsnoopy** [pieroit/cheshire-cat#220]
(As per discussion on the C-cat Discord server, specifically in the #bug-reports channel on May 5th, 2023, at 18:44, it was suggested that I open an issue to address this concern.)

The problem: the cat sometimes filter-out answers from the LLM

**Comment by pieroit** [comment]
HyDE embedding is deactivated by default.
You can personalize how the cat recalls memories bu intercepting the [cat_recall_query](https://github.com/pieroit/cheshire-cat/blob/main/core/cat/mad_hatter/core_plugin/hooks/flow.py#L20) hook
