### ISSUE TITLE
Docker compose up not working on PopOS

### ISSUE THREAD

**Issue by joke2k** [pieroit/cheshire-cat#247]
Ciao, I was trying to start the project on my local PopOS but at the end of the `docker compose up` I receive this error:
```
...
 ✔ Container cheshire_cat_vector_memory  Running                                                                                                             0.0s 
Attaching to cheshire_cat_core, cheshire_cat_vector_memory
Error response from daemon: driver failed programming external connectivity on endpoint cheshire_cat_core (01db852296190ac4fd1112a08e4f4f47d1da28ade2bf8d30b82277f14426237b):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 1865 -j DNAT --to-destination 172.20.0.3:80 ! -i br-efd7377b74a4: iptables v1.8.7 (nf_tables): unknown option "--dport"
Try `iptables -h' or 'iptables --help' for more information.
 (exit status 2))
```

Looking around I found that seems something related to my local iptables setup.

```
$ uname -a
Linux oryx 6.2.6-76060206-generic #202303130630~1681329778~22.04~d824cd4 SMP PREEMPT_DYNAMIC Wed A x86_64 x86_64 x86_64 GNU/Linux

$ dockerd --version
Docker version 24.0.2, build 659604f

$ iptables -V
iptables v1.8.7 (nf_tables)
```

Any ideas how to fix it?

Thank you very much for reading this.

https://serverfault.com/questions/563033/iptables-error-unknown-option-dport
https://github.com/moby/moby/issues/38759
https://developers.redhat.com/blog/2020/08/18/iptables-the-two-variants-and-their-relationship-with-nftables

**Comment by pieroit** [comment]
I'm sorry mate this is not an issie with the cat, but with your local network setup.
Maybe this can help:
https://pieroit.github.io/cheshire-cat/faq/#errors

Closing the issue
