### ISSUE TITLE
In the README warn that `docker-compose` may be `docker compose`

### ISSUE THREAD

**Issue by danieleongari** [pieroit/cheshire-cat#248]
It may sound bogus for experienced users, but since there is some dissemination effort (see ROADMAP) to make this easy to set-up for new users, it may be helpful to warn that in newer docker compose plugin installation, the command is `docker compose` instead of `docker-compose`

https://stackoverflow.com/questions/66514436/difference-between-docker-compose-and-docker-compose

**Comment by pieroit** [comment]
Can you update the readme and possibly the docs branch with this?
