### ISSUE TITLE
Admin still connecting to localhost:1865 despite custom .env

### ISSUE THREAD

**Issue by nunzilorenzo** [pieroit/cheshire-cat#256]
a few days ago i installed cheshire cat in ubuntu vps and i haved this issues :
![image](https://github.com/pieroit/cheshire-cat/assets/104850039/8d7c2120-9971-4031-88c9-dac178f44451)

**Comment by zAlweNy26** [comment]
Try updating the cat, you still have the old UI

**Comment by nunzilorenzo** [comment]
yes i tried with 3 different version and the error was the same

**Comment by zAlweNy26** [comment]
You should use the latest version, and also send the console logs

**Comment by nunzilorenzo** [comment]
now i have the last version, where i can find the log ?

**Comment by zAlweNy26** [comment]
If you are starting it from the console, these are the logs, if you are using Docker Desktop, just open the container and the logs will show up

**Comment by nunzilorenzo** [comment]
im still here :D

**Comment by pieroit** [comment]
The admin is connecting to localhost:1865 because during admin build there was no access to env variables.
It's a bug to be fixed, but you can easily use the rest api

**Comment by pieroit** [comment]
solution offered in #257 , closing this and leaving that one open
