### ISSUE TITLE
Getting openAI response as Stream

### ISSUE THREAD

**Issue by alessandroperetti** [pieroit/cheshire-cat#258]
Hi all,
is it possible to get response from openAI in chunks or tokens?
I mean something like  `stream = True`  in chat completions.
The reason is that I don't want to wait for the whole response before output.

Thanks

**Comment by pieroit** [comment]
Not really, there is an agent in the cat that makes multiple calls to the LLM

Also, not all LLMs support streaming

Let's see in the future
