### ISSUE TITLE
Add endpoints to list and delete memory contents

### ISSUE THREAD

**Issue by pieroit** [pieroit/cheshire-cat#29]
Anything you say or upload to the cat is vectorized and store in a vector db.

It should be possible to read and delete memories via endpoints, since any vector has metadata on its source.

**Comment by pieroit** [comment]
It would be even cooler to manage uploads via a langchain Tool
(e.g. "list documents I uploaded" or "delete document xxx.pdf")

**Comment by pieroit** [comment]
Some memory endpoints have been added by @peppicus , closing this issue.

**Comment by giodegas** [comment]
how about the possibility to list the uploaded documents/sources?

Maybe like:

    /memory/list

**Comment by pieroit** [comment]
> how about the possibility to list the uploaded documents/sources?
> 
> Maybe like:
> 
> ```
> /memory/list
> ```

@giodegas memories are inserted with a `source` so it would be possible if qdrant can extract unique values for metadata.

Endpoint would be `GET /memory/sources`

Are you willing to work on this?

Start digging here
https://github.com/cheshire-cat-ai/core/blob/main/core/cat/rabbit_hole.py#L184

**Comment by giodegas** [comment]
Yes indeed , I will try as soon I can.
Thank you @pieroit .
