### ISSUE TITLE
Implement a more flexible CSS modules naming strategy to facilitate external contributions and allow effortless CSS class overrides by plugin creators

### ISSUE THREAD

**Issue by antonioru** [pieroit/cheshire-cat#32]
### Problem

Currently, the CSS modules naming strategy used by VITE is not very flexible, which can make it difficult for external contributors and plugin creators to customise the CSS classes. This can be especially problematic when trying to apply custom styling or override existing styles

### Approach 

Given that we are using VITE as a bundler, we can take advantage of its built-in support for CSS modules and its various configuration options. Specifically, we can explore the css.modules option in VITE, which provides several options for customizing the CSS modules behavior, including the ability to specify custom naming conventions and post-processing steps.

For more information on how to configure CSS modules in VITE, see the [official VITE documentation](https://vitejs.dev/config/shared-options.html#css-modules).

**Comment by antonioru** [comment]
I'm still considering the best namespace format to use, but perhaps something along the lines of "ccat-${fileName}-${className}" would be a good starting point

**Comment by pieroit** [comment]
Agree on ccat-${fileName}-${className}
Kudos
