### ISSUE TITLE
AssertionError()

### ISSUE THREAD

**Issue by niatro** [pieroit/cheshire-cat#59]
Hi Piere, thanks for this proyect...   is wonderful.
Look I have the netxt error in the UI
![image](https://user-images.githubusercontent.com/34010695/227792992-f49f1592-31bb-4e14-ab42-57fe1284d1aa.png)
But in the cmd terminal I see the correct answer
![image](https://user-images.githubusercontent.com/34010695/227793069-8569d8de-5c1f-4491-9caf-808e9450c13b.png)

The terminal throw the next error:
web       | Traceback (most recent call last):
web       |   File "/app/./cat/main.py", line 57, in websocket_endpoint
web       |     cat_message = cheshire_cat(user_message)
web       |   File "/app/./cat/looking_glass.py", line 167, in __call__
web       |     episodic_memory_content = self.recall_memories_from_embedding(
web       |   File "/app/./cat/looking_glass.py", line 114, in recall_memories_from_embedding
web       |     memories = self.memory[collection].similarity_search_with_score_by_vector(
web       |   File "/usr/local/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 151, in similarity_search_with_score_by_vector
web       |     scores, indices = self.index.search(np.array([embedding], dtype=np.float32), k)
web       |   File "/usr/local/lib/python3.9/site-packages/faiss/class_wrappers.py", line 329, in replacement_search
web       |     assert d == self.d
web       | AssertionError

And Chat GPT4 says:

The error you are experiencing appears to be an AssertionError caused by a discrepancy in the dimension of the embedding vectors in the application you are using. Here's an explanation of the error in detail:

1. The error originates in the file looking_glass.py in the function recall_memories_from_embedding.
2. This function attempts to retrieve memories using a similarity search method based on embeddings.
3. The error occurs in the call to the similarity_search_with_score_by_vector method of the Faiss class, which is located in the faiss.py file.
4. The AssertionError is generated in the replacement_search function in class_wrappers.py of the Faiss library, when it checks whether the dimension d of the search vector matches the dimension d of the Faiss index.

The solution to this issue will depend on the underlying cause of the discrepancy in the dimensions of the embedding vectors. Here are some ideas for troubleshooting the issue:

1. Verify embedding configuration: Ensure that the application is using the correct configuration for the embeddings, including the models and dimensions of the vectors. Check if there is any preprocessing or transformation step for the embeddings that should be performed before using them in the similarity search.
2. Debug the data flow: Investigate how data is passed through the application and how embeddings are manipulated. Ensure that all steps in the data flow are consistent in terms of dimensions and data types.
3. Review documentation and code: Refer to the documentation and source code of the Faiss library and the application you are working on to understand how embeddings and search indexes should be configured and used. This can help you identify the cause of the error and fix it.
4. Update libraries: Ensure that you are using the most recent versions of the involved libraries. Sometimes, errors can be caused by issues in older versions that have already been fixed in later versions.

If after investigating these aspects you still cannot resolve the issue, consider reaching out to the developers of the application or the Faiss library for assistance or to report a possible bug.

**Comment by pieroit** [comment]
Oh yes thank you for finding this. The reason is that the cat started without a key and created a memory with a different dimensionality than the one used for the OpenAI service.

I'll leave this issue open with a more explicit title so I'll fox this.

**Comment by pieroit** [comment]
@niatro to fix just delete the file:
web/long_term_memory

**Comment by niatro** [comment]
Works!!!   wonderful
