### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by Mte90** [pieroit/cheshire-cat#62]
It can be interesting to save the output/input not just in the database but also divided by user.
In this way in the UI it is possible to see previous chats and different user settings.

There is https://pypi.org/project/fastapi-users/ that already use sqlalchemy and add the various endpoints.

**Comment by pieroit** [comment]
Yes! Can you make a minimal PR for user management? Just dependencies and another table in the already present sqlite (which is just used for settings at the moment)

After that (I need to refactor some code) we we make the settings user based and after that we integrate users with memory and agent.

Thank you!
