### ISSUE TITLE
Python Code organization

### ISSUE THREAD

**Issue by Mte90** [pieroit/cheshire-cat#63]
Just some thoughts as the code can be reorganized:

* change `web` name to `backend` (in this way is clear the different between the `frontend` folder)
* ~~every file should include a documentation head line to understand what is the purpose, ex: rabbit_hole.py~~ moved to #106
* ~~in python and in other language there is the convention that the file name correspond to the class, a file `looking_glass.py` that has a function `CheshireCat` is not clear~~

Clean `main.py`, to just execute the backend (and initialize stuff):

* ~~move from all the endpoints in a specific file (like `routes.py`)~~
* move the version string to a dedicated file like `version.txt`, in this wat the version is not hardcoded

Organize differently the endpoints:

* ~~In main.py and setting.py there are endpoints, makes more sense to do a folder `routes` with 2 files (now): settings.py and base.py (or a better name)~~

Divide `CheshireCat` in 2 different files, one is the cat and another is just the boostrap like for the db and so on.
Also in thinking about the plugin stuff everything in the code that calls external frameworks/libraries like for langchain should be handled by a dedicated class so it is more easy to extend it or change it. https://github.com/pieroit/cheshire-cat/blob/main/web/cat/looking_glass.py#L61

Probably the files in the config folder should explains better what is the purpose. I think that is better if they are in the db folder as they are just the models for those data.

**Comment by pieroit** [comment]
Lots of great suggestions.
Working on some right now thanks

**Comment by pieroit** [comment]
I made a refactor so all endpoints are all in the `routes` folder.
Leaving this issue open to follow the other suggestions.

About the plugin system (the `mad_hatter`): I prefer to keep it easy at the moment (just functions with decorators, with implicit registration). I cannot understand if that is possible with pluggy (maybe yes), let me some time to study it. I like the hookspec concept. Amazing tool !

**Comment by Mte90** [comment]
The version is still on https://github.com/pieroit/cheshire-cat/blob/main/web/cat/routes/openapi.py#L13 this is not simplify for the future when you have to bump that, better to move to a file to read.
I just marked as done some of the previous hints in the first comment.
I don't understand https://github.com/pieroit/cheshire-cat/blob/main/web/cat/routes/openapi.py this file in the routes folder but it isn't a route just a function, to me is better in the config folder or in `utils`.

About plugins yes until the code organization changes aren't finished is earlier but as the project is starting now better to do the right things now before the codebase become more complicate. Also to avoid that we have a wuickstart plugin that instead is a real plugin.

For the other suggestion I think it is the case to add documentation in every single file at the top, like the python standard and the other things.

**Comment by pieroit** [comment]
> The version is still on https://github.com/pieroit/cheshire-cat/blob/main/web/cat/routes/openapi.py#L13 this is not simplify for the future when you have to bump that, better to move to a file to read.

> I don't understand https://github.com/pieroit/cheshire-cat/blob/main/web/cat/routes/openapi.py this file in the routes folder but it isn't a route just a function, to me is better in the config folder or in `utils`.

Can you do both of them?

> For the other suggestion I think it is the case to add documentation in every single file at the top, like the python standard and the other things.

Will do thanks

> Divide CheshireCat in 2 different files, one is the cat and another is just the boostrap like for the db and so on.
Also in thinking about the plugin stuff everything in the code that calls external frameworks/libraries like for langchain should be handled by a dedicated class so it is more easy to extend it or change it. https://github.com/pieroit/cheshire-cat/blob/main/web/cat/looking_glass.py#L61

Yes let me think about this because LLMs and embedders are already wrapped, also the vector memory, but in different ways.

**Comment by Mte90** [comment]
Reading the code I think that the majority of things are already done.
Apart the one remain the first comment, I suggest that where it is used langchain it should be managed by another class like for https://github.com/pieroit/cheshire-cat/blob/main/web/cat/memory.py#L36 and on https://github.com/pieroit/cheshire-cat/blob/main/web/cat/rabbit_hole.py
In this in the future if it is needed to use a different system to store things there aren't direct reference to this (extend, replaced and so on by a plugin).

**Comment by pieroit** [comment]
> Reading the code I think that the majority of things are already done.

Great! I followed many of your suggestions, thanks.

> Apart the one remain the first comment, I suggest that where it is used langchain it should be managed by another class like for https://github.com/pieroit/cheshire-cat/blob/main/web/cat/memory.py#L36 and on https://github.com/pieroit/cheshire-cat/blob/main/web/cat/rabbit_hole.py

Agree on encapsulation, as soon as the codebase stabilizes a little

> In this in the future if it is needed to use a different system to store things there aren't direct reference to this (extend, replaced and so on by a plugin).

Yep
