### ISSUE TITLE
Integration with HuggingFace

### ISSUE THREAD

**Issue by nickprock** [pieroit/cheshire-cat#66]
Huggingface is the most popular hub for LLMs. Given the open source philosophy of the project I think integration and collaboration with the HuggingFace community could be great

**Comment by pieroit** [comment]
Hi @nickprock thank you for reaching out.
Support for HuggingFace is partially implemented, all config classes are ready [here](https://github.com/pieroit/cheshire-cat/blob/main/web/cat/config/llm.py) to use:
- HF endpoints
- HF hub
- HF pipeline (local models)

The first two just need to be tested from plugins, while the latest would require a separate container (yet to do).

Can you tell me which of the three is in your interest at the moment so I can help you try it out, and if you feel like it contribute to the cat?

**Comment by nickprock** [comment]
Ho @pieroit at the moment the first die would be fine.  I'd love to try them out and write some examples.

**Comment by pieroit** [comment]
In the [example plugin](https://github.com/pieroit/cheshire-cat/tree/main/web/cat/plugins/quickstart_cat_plugin) you can find this hook:

```python
@hook
def get_language_model(cat):

    if "OPENAI_KEY" in os.environ:
        llm = llms.LLMOpenAIChatConfig.get_llm_from_config(
            {
                "openai_api_key": os.environ["OPENAI_KEY"],
                # "model_name": "gpt-3.5-turbo" # TODO: allow optional kwargs
            }
        )
    else:
        llm = llms.LLMDefaultConfig.get_llm_from_config({})

    return llm
```

Should be substituted with something like:

```python
@hook
def get_language_model(cat):

    llm = llms.LLMHuggingFaceEndpointConfig.get_llm_from_config(
        {
             "endpoint_url": "YOUR ENDPOINT URL"
             "huggingfacehub_api_token": "YOUR HF API TOKEN"
        }
    )
    
    return llm
```

The same should be done for the embedder [config classes](https://github.com/pieroit/cheshire-cat/blob/main/web/cat/config/embedder.py) and [plugin hook](https://github.com/pieroit/cheshire-cat/blob/main/web/cat/plugins/quickstart_cat_plugin/models.py#L30), but config classes are not yet implemented. You can bypass them by using [langchain directly](https://python.langchain.com/en/latest/ecosystem/huggingface.html#embeddings)

Sorry for the mess :')
Tell me if you get any issue. Out of office right now but available to help. Thank you!

**Comment by nickprock** [comment]
HuggingFaceEmbeddings from langchain.embeddings has a default sentence transformers [all-mpnet-base-v2](https://huggingface.co/sentence-transformers/all-mpnet-base-v2). At the moment I left this without including the possibility for the user to indicate a model so as not to raise the complexity and because [the performances are good](https://www.sbert.net/docs/pretrained_models.html#model-overview)

**Comment by nickprock** [comment]
I have submitted the PR for endpoints. Code is as simple as possible to choose between hub and endpoint. For Embeddings I continue to use the Hub

**Comment by nickprock** [comment]
* [x] HF Hub
* [x] HF Endpoints
* [ ] WIP HF Embeddings

> HF Local Models needs a new container

**Comment by pieroit** [comment]
Thank you for this!
Just merged your latest PR.
For version 1 the plan is to make all this configurable via a web UI

To use custom local models there should be an adapter in the cat able to call an external container exposing specific endpoints, for example:
- POST `/generate` for LLM
- POST `/embed` for embedding

We should define a rest api spec first, then write the adapters in the cat, then we can setup and provide the community custom containers (the most important being the one hosting and running HF models)

Also this finally opens up possibility for local, gpu driven models
