### ISSUE TITLE
navigation from smartphone returns error

### ISSUE THREAD

**Issue by alessandro-Petrone** [pieroit/cheshire-cat#72]
https://lysvz.localtonet.com/
something went wrong whhile connecting to the server. pleasetry agin later

**Comment by pieroit** [comment]
I see this error in the console:

![Screenshot from 2023-04-03 18-07-35](https://user-images.githubusercontent.com/6328377/229566225-5e2c4220-15a0-4aa1-941b-1af9fd5b6b86.png)

The frontend is still calling localhost, in fact if I run the cat on my computer and talk to your website:

![Screenshot from 2023-04-03 18-03-44](https://user-images.githubusercontent.com/6328377/229565475-67985c52-4180-4beb-abed-cd291d88cab3.png)

The frontend should call the proper backend, which is a computer on which the cat is running!
So not localhost, but `lysvz.localtonet.com:1865/ws`

Please let me know, I'll show this issue to the fronend dev @antonioru.

Thanks!!!

**Comment by pieroit** [comment]
Should be solved by #117
