### ISSUE TITLE
UPLOAD NEW CONTENT WITH "SCORE" TO DRIVE "CAT" ANSWER

### ISSUE THREAD

**Issue by ExtremeSRL** [pieroit/cheshire-cat#74]
Do you think it is feasible to define an attribute of "authoritativeness" to the uploaded documents, a score between 0 and 1 where 1 is the highest authoritativeness, and to be able to steer the Cat's choices in formulating responses, prioritizing information sources with priority 1.
This would allow the Cat, given equal available content, to choose the one with higher score.
It could be useful to weigh reliable sources from less reliable ones.

**Comment by pieroit** [comment]
@ExtremeSRL can be done via plugin!

**Comment by pieroit** [comment]
Allowing plugin to edit memory metadata is being discussed in #157
