### ISSUE TITLE
Plugin list

### ISSUE THREAD

**Issue by antonioru** [pieroit/cheshire-cat#92]
The backend should provide a list of available plugins through the /plugins endpoint. This list will include the plugin's name, description, and a unique id. The unique id may simply be the name of the folder that the plugin is stored in. To allow end users to define plugin metadata, the suggested approach is to have a non-mandatory plugin.json file stored in each plugin's directory where the user can define both name and description (as well as future metadata such as the JSON schema of the configuration).

```
// plugin.json
{
  "name": "MyCustomPlugin",
  "description": "Makes the cat cool af" 
}
```

if the plugin.json file is not defined then the backend should default to the values from the folder name.

A possible response from the /plugins endpoint will then be:

```
[
 { 
	 id: "cool-plugin", 
	 name: "MyCustomPlugin", 
	 description: "Makes the cat cool af" 
  },
]
```

The front end should fetch the list of available plugins and display them under the /plugins route as a read-only list. Create a new pluginsSlice using redux and follow the defined best practice on how to handle async states. At the moment, no interaction is scheduled.

**Comment by AngyDev** [comment]
Hi!! I'd like to work on this issue by creating a list of available plugins on the frontend side. @pieroit should you assign it to me?

**Comment by pieroit** [comment]
Thank you @AngyDev, I will take care of the backend endpoints
