### ISSUE TITLE
Display reasoning

### ISSUE THREAD

**Issue by antonioru** [pieroit/cheshire-cat#93]
We want to display the reasoning behind a response from the CheshireCat, to provide users with greater transparency and insight into the decision-making process. To do this, we will leverage the Sidebar component to present the content of the reasoning object, which is already sent from the backend. The reasoning object is defined as follows:

```
{
    "input": "What is Python?",
    "episodic_memory": [
      {
        "page_content": "it is for fictional purposes ",
        "lookup_str": "",
        "metadata": {
          "source": "user",
          "when": 1680432386.7730486,
          "text": "it is for fictional purposes "
        },
        "lookup_index": 0,
        "score": 0.5044264793395996
      },
      {
        "page_content": "Write a 400 words post on how Ai is going to change the world",
        "lookup_str": "",
        "metadata": {
          "source": "user",
          "when": 1680432337.0415337,
          "text": "Write a 400 words post on how Ai is going to change the world"
        },
        "lookup_index": 0,
        "score": 0.5165414810180664
      },
      {
        "page_content": "write the introduction of a novel that talks about how the world has been taken over by the AI",
        "lookup_str": "",
        "metadata": {
          "source": "user",
          "when": 1680432429.13744,
          "text": "write the introduction of a novel that talks about how the world has been taken over by the AI"
        },
        "lookup_index": 0,
        "score": 0.5386247634887695
      },
      {
        "page_content": "nice, write a 670 words paragraph on who Ai will take over humanity",
        "lookup_str": "",
        "metadata": {
          "source": "user",
          "when": 1680432365.206487,
          "text": "nice, write a 670 words paragraph on who Ai will take over humanity"
        },
        "lookup_index": 0,
        "score": 0.5566583275794983
      },
      {
        "page_content": "I am the Cheshire Cat",
        "lookup_str": "",
        "metadata": {
          "who": "cheshire-cat",
          "when": 1679948291.703731,
          "text": "I am the Cheshire Cat"
        },
        "lookup_index": 0,
        "score": 0.564825177192688
      }
    ],
    "declarative_memory": [
      {
        "page_content": "I am the Cheshire Cat",
        "lookup_str": "",
        "metadata": {
          "who": "cheshire-cat",
          "when": 1679948292.8870578,
          "text": "I am the Cheshire Cat"
        },
        "lookup_index": 0,
        "score": 0.564825177192688
      }
    ],
    "chat_history": "",
    "output": "Python is a programming language used in various applications such as web development, data analysis, machine learning, and artificial intelligence.",
    "intermediate_steps": []
  }
```

**Comment by PaperBackPear3** [comment]
> We want to display the reasoning behind a response from the CheshireCat, to provide users with greater transparency and insight into the decision-making process. To do this, we will leverage the Sidebar component to present the content of the reasoning object, which is already sent from the backend. The reasoning object is defined as follows:
> 
> ```
> {
>     "input": "What is Python?",
>     "episodic_memory": [
>       {
>         "page_content": "it is for fictional purposes ",
>         "lookup_str": "",
>         "metadata": {
>           "source": "user",
>           "when": 1680432386.7730486,
>           "text": "it is for fictional purposes "
>         },
>         "lookup_index": 0,
>         "score": 0.5044264793395996
>       },
>       {
>         "page_content": "Write a 400 words post on how Ai is going to change the world",
>         "lookup_str": "",
>         "metadata": {
>           "source": "user",
>           "when": 1680432337.0415337,
>           "text": "Write a 400 words post on how Ai is going to change the world"
>         },
>         "lookup_index": 0,
>         "score": 0.5165414810180664
>       },
>       {
>         "page_content": "write the introduction of a novel that talks about how the world has been taken over by the AI",
>         "lookup_str": "",
>         "metadata": {
>           "source": "user",
>           "when": 1680432429.13744,
>           "text": "write the introduction of a novel that talks about how the world has been taken over by the AI"
>         },
>         "lookup_index": 0,
>         "score": 0.5386247634887695
>       },
>       {
>         "page_content": "nice, write a 670 words paragraph on who Ai will take over humanity",
>         "lookup_str": "",
>         "metadata": {
>           "source": "user",
>           "when": 1680432365.206487,
>           "text": "nice, write a 670 words paragraph on who Ai will take over humanity"
>         },
>         "lookup_index": 0,
>         "score": 0.5566583275794983
>       },
>       {
>         "page_content": "I am the Cheshire Cat",
>         "lookup_str": "",
>         "metadata": {
>           "who": "cheshire-cat",
>           "when": 1679948291.703731,
>           "text": "I am the Cheshire Cat"
>         },
>         "lookup_index": 0,
>         "score": 0.564825177192688
>       }
>     ],
>     "declarative_memory": [
>       {
>         "page_content": "I am the Cheshire Cat",
>         "lookup_str": "",
>         "metadata": {
>           "who": "cheshire-cat",
>           "when": 1679948292.8870578,
>           "text": "I am the Cheshire Cat"
>         },
>         "lookup_index": 0,
>         "score": 0.564825177192688
>       }
>     ],
>     "chat_history": "",
>     "output": "Python is a programming language used in various applications such as web development, data analysis, machine learning, and artificial intelligence.",
>     "intermediate_steps": []
>   }
> ```



If possible, assign this to me.

and i have some questions? how would that work? the reasoning shoud be dispayed for each messsage received from the backend?
taking for example the structure received on the input "What is Python?" there it's not using anything from his local "storage" it's just the llm's answer to that. am I getting this right?


thanks :)

**Comment by pieroit** [comment]
Hi @PaperBackPear3 hang on as there is discussion on the admin at the moment. We will back to you ASAP thanks
