### ISSUE TITLE
Markdown support for chat

### ISSUE THREAD

**Issue by antonioru** [pieroit/cheshire-cat#97]
We want to enable Markdown support in our CheshireCat project. By design, most language models use Markdown in their responses, so we will be editing the MessageBox component using the Remark library located at https://github.com/remarkjs/remark. This will enable us to support markdown responses from the CheshireCat.

**Comment by antonioru** [comment]
Relates to #95

**Comment by elio1fiore** [comment]
Can you assign me this implementation?

**Comment by pieroit** [comment]
@elio1fiore assigned to you.
Please male sure to be aligned on this with @antonioru as he is the most knowledgeable on the frontend admin ;)
Thank you

**Comment by pieroit** [comment]
@elio1fiore any news?

**Comment by antonioru** [comment]
@pieroit can you please reassign this to me?

**Comment by fedestyla** [comment]
I've spoken to Antonio about this one. Could you assign it to me?

**Comment by pieroit** [comment]
welcome @fedestyla

**Comment by fedestyla** [comment]
Initial support for markdown has been added with PR -> https://github.com/pieroit/cheshire-cat/pull/146

**Comment by fedestyla** [comment]
Major exclusions/outstanding work:
- Syntax highlight currently not implemented for any language
- Blocks need better styling
- Table need better styling

**Comment by fedestyla** [comment]
@pieroit Sure, here are the 3 different issues. Feel free to assign those to me!

- https://github.com/pieroit/cheshire-cat/issues/164
- https://github.com/pieroit/cheshire-cat/issues/165
- https://github.com/pieroit/cheshire-cat/issues/166

**Comment by antonioru** [comment]
@fedestyla that's great man, thank you so much! 

On a separate (but not so much) note: I've noticed the instance of the Remarkable tool was created inside the component which might lead to performance issues so I moved it outside :3 
just FYI 

```
const markdown = new Remarkable({ linkify: true, breaks: true, typographer: true }).use(linkify)
markdown.inline.ruler.enable(['sup', 'sub'])
markdown.core.ruler.enable(['abbr'])
markdown.block.ruler.enable(['footnote', 'deflist'])

/**
 * Displays a single chat message.
 * It is used to display both the user's messages and the Cheshire Cat's responses.
 */
const MessageBox: FC<MessageBoxProps> = ({ text, sender, className, ...rest }) => {
  const isBot = sender === 'bot'
  const classList = clsx(style.message, isBot ? style.bot : style.user, className)

  return (
    <article className={classList} {...rest}>
      {isBot && (<div className={style.avatar}>😺</div>)}
      <span className={style.content} dangerouslySetInnerHTML={{ __html: markdown.render(text) }} />
    </article>
  )
}

```
